name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: go vet
        run: go vet ./...

      - name: go test
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57.2

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: coverage.out
        continue-on-error: true
